# Generated by Django 6.0.4 on 2026-04-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                blank=True, default="icon.png", null=True, upload_to="profiel_pictures/"
            ),
        ),
    ]
