# Generated by Django 6.0.4 on 2026-04-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verified",
        ),
    ]
